#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy
server_config=\
"
frontend  nymore-frontend
        bind *:80
        mode http
        default_backend nymore-backend
backend nymore-backend
        balance roundrobin
        server 438976-web-01 34.207.221.178:80 check
        server 438976-web-02 34.224.83.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
